# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xukTSQ6B2VtQY9cOWXxjFXsedjL6v7Rv
"""

# Install required libraries

!pip install pandas numpy scikit-learn
!pip install sentence-transformers
!pip install faiss-cpu
!pip install langchain

import pandas as pd
import numpy as np

from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

from sentence_transformers import SentenceTransformer
import faiss

data = {
    "plant_id": ["P1","P2","P3","P4","P5","P6"],
    "water_usage": [500,520,510,900,505,495],
    "energy_consumption": [300,290,310,320,305,295],
    "chemical_level": [50,55,52,70,51,49],
    "temperature": [40,39,41,45,40,38]
}

df = pd.DataFrame(data)

df

features = df[[
    "water_usage",
    "energy_consumption",
    "chemical_level",
    "temperature"
]]

scaler = StandardScaler()

scaled_features = scaler.fit_transform(features)

scaled_features

model = IsolationForest(
    contamination=0.15,
    random_state=42
)

model.fit(scaled_features)

df["anomaly"] = model.predict(scaled_features)

df

df["status"] = df["anomaly"].apply(
    lambda x: "ALERT ⚠️" if x == -1 else "Normal"
)

df[["plant_id","status"]]

df["sustainability_score"] = 100 - (
    abs(df["water_usage"] - df["water_usage"].mean()) * 0.05 +
    abs(df["energy_consumption"] - df["energy_consumption"].mean()) * 0.1 +
    abs(df["chemical_level"] - df["chemical_level"].mean()) * 0.2
)

df[["plant_id","sustainability_score"]]

def risk_level(score):
    if score > 80:
        return "Safe"
    elif score > 50:
        return "Moderate"
    else:
        return "Critical"

df["risk_level"] = df["sustainability_score"].apply(risk_level)

df[["plant_id","sustainability_score","risk_level"]]

documents = [
"""
Water recycling systems can reduce industrial plant water usage by up to 30 percent.
Cooling towers are a major source of water consumption.
Regular inspection of cooling tower efficiency can prevent water loss.
Leak detection systems help identify pipeline water losses.
""",

"""
Energy optimization in industrial plants can be achieved using variable speed pumps,
heat recovery systems, and automation of process controls.
Monitoring energy consumption trends helps detect inefficient machinery.
""",

"""
Chemical safety management requires monitoring chemical dosing levels.
Excess chemical concentration may indicate sensor calibration issues
or overuse of treatment chemicals.
Regular calibration of monitoring equipment is recommended.
"""
]

model_embed = SentenceTransformer("all-MiniLM-L6-v2")

doc_embeddings = model_embed.encode(documents)

doc_embeddings.shape

dimension = doc_embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(np.array(doc_embeddings))

def retrieve_document(query):

    query_vector = model_embed.encode([query])

    distances, indices = index.search(np.array(query_vector), k=1)

    return documents[indices[0][0]]

query = "How to reduce water consumption in a plant?"

result = retrieve_document(query)

print(result)

def generate_recommendation(plant_id):

    plant_data = df[df["plant_id"] == plant_id]

    if plant_data["status"].values[0] == "Normal":
        return "Plant operating normally. No major sustainability risks detected."

    query = "How to reduce water usage and improve industrial sustainability?"

    doc = retrieve_document(query)

    recommendation = f"""
EcoSentinel AI Insight

Plant {plant_id} shows abnormal resource usage.

Relevant Sustainability Guidance:
{doc}

Recommended actions:
• Inspect cooling towers
• Check pipeline leakages
• Implement water recycling systems
"""

    return recommendation

print(generate_recommendation("P4"))

def generate_report():

    report = "EcoSentinel Sustainability Report\n\n"

    for _, row in df.iterrows():

        report += f"""
Plant: {row['plant_id']}
Status: {row['status']}
Sustainability Score: {round(row['sustainability_score'],2)}
Risk Level: {row['risk_level']}
"""

        if row["status"] == "ALERT ⚠️":
            report += generate_recommendation(row["plant_id"])

        report += "\n-----------------------------\n"

    return report

print(generate_report())

df[["plant_id","status","sustainability_score","risk_level"]]

import random
import time

def simulate_live_data():
    while True:

        water = random.randint(480,520)
        energy = random.randint(290,310)
        chemical = random.randint(48,55)
        temp = random.randint(38,42)

        print("New Sensor Reading:")
        print(water, energy, chemical, temp)

        time.sleep(5)

import matplotlib.pyplot as plt

plt.bar(df["plant_id"], df["sustainability_score"])
plt.title("Plant Sustainability Score")
plt.show()